# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpDTMnbW0i7KteBXLkK1F8_Bl4hbWbWi
"""

import torch
print(torch.cuda.is_available()) # cuda 사용 가능?
print(torch.cuda.device_count()) # 갯수
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(torch.cuda.current_device()))
