# -*- coding: utf-8 -*-
"""Image_Noise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eZcEEF6wgwnXAdwQHcUuUo9KNaVYRqNw
"""

import cv2
import matplotlib.pyplot as plt
import urllib.request
import numpy as np
import imutils

def url_to_image(url):
  resp = urllib.request.urlopen(url)
  image = np.asarray(bytearray(resp.read()), dtype="uint8")
  image = cv2.imdecode(image, cv2.IMREAD_COLOR)

  return image

if __name__ == '__main__':
  # image url
  img_url = "https://image.edaily.co.kr/images/Photo/files/NP/S/2020/09/PS20090500038.jpg"

  img = url_to_image(img_url) # cv2 image

  #img = cv2.resize(img, (224, 224))
  # new rotate
  rotated = imutils.rotate(img, 45)
  cv2.imwrite('./test.jpg', rotated)
  
  # rotation & mirror mode & bright & dark
  img_rot = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE) # 시계방향으로 90도 회전
  img_mirror = cv2.flip(img, 1)

  bright = np.ones(img.shape, dtype = "uint8") * 100
  dark = np.ones(img.shape, dtype = "uint8") * 50

  img_bright = cv2.add(img, bright)
  img_dark = cv2.subtract(img, dark)

  # image show

  plt.subplot(1,5,1)
  plt.imshow(img)

  plt.subplot(1,5,2)
  plt.imshow(img_rot)

  plt.subplot(1,5,3)
  plt.imshow(img_mirror)

  plt.subplot(1,5,4)
  plt.imshow(img_bright)

  plt.subplot(1,5,5)
  plt.imshow(rotated)

  plt.show()



























